modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${minecraft_version}-${mod_version}"
    displayName = "${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/BlatFan/mod_updates/refs/heads/main/blatapi/updates.json"
    displayURL="https://github.com/BlatFan/mod_updates/blob/main/blatapi/links.md"
    logoFile="icon.png"
    credits="Thanks to MaxBogomol"
    authors = "${mod_authors}"
    description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies."${mod_id}"]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
